export enum MineralCategory {
  ELEMENTS = 'elements',
  SULFIDES = 'sulfides',
  HALIDES = 'halides',
  OXIDES = 'oxides',
  CARBONATES = 'carbonates',
  BORATES = 'borates',
  SULFATES = 'sulfates',
  PHOSPHATES = 'phosphates',
  SILICATES = 'silicates',
  ORGANIC = 'organic',
  UNKNOWN = 'unknown'
};

export enum MineralClass {
  ELEMENTS = 'elements',
  SULFIDES = 'sulfides',
  SULFOSALTS = 'sulfosalts',
  HALIDES = 'halides',
  OXIDES = 'oxides',
  HYDROXIDES = 'hydroxides',
  ARSENITES = 'arsenites',
  CARBONATES = 'carbonates',
  NITRATES = 'nitrates',
  BORATES = 'borates',
  SULFATES = 'sulfates',
  CHROMATES = 'chromates',
  MOLYBDATES = 'molybdates',
  PHOSPHATES = 'phosphates',
  ARSENATES = 'arsenates',
  ORGANIC = 'organic',
  SILICATES = 'silicates',
  UNKNOWN = 'unknown'
};

export enum CrystalHabit {
  ACICULAR = 'acicular',
  ARBORESCENT = 'arborescent',
  CAPILLARY = 'capillary',
  COLLOFORM = 'colloform',
  CONCENTRIC = 'concentric',
  DENDRITIC = 'dendritic',
  DRUSE = 'druse',
  FIBROUS = 'fibrous',
  FOLIATED = 'foliated',
  GRANULAR = 'granular',
  HOPPER = 'hopper',
  OOLITHIC = 'oolithic',
  PISOLITIC = 'pisolitic',
  PLATY = 'platy',
  PLUMOSE = 'plumose',
  RADIAL = 'radial',
  RETICULATED = 'reticulated',
  ROSETTE = 'rosette',
  STALACTITIC = 'stalactitic',
  STELLATE = 'stellate',
  AMYGDALOIDAL = 'amygdaloidal',
  HEMIMORPHIC = 'hemimorphic',
  MASSIVE = 'massive',
  SCEPTERED = 'sceptered',
  CUBIC = 'cubic',
  DODECAHEDRAL = 'dodecahedral',
  ENANTIOMORPHIC = 'enantiomorphic',
  HEXAGONAL = 'hexagonal',
  ICOSITETRAHEDRAL = 'icositetrahedral',
  OCTAHEDRAL = 'octahedral',
  PRISMATIC = 'prismatic',
  RHOMBOHEDRAL = 'rhombohedral',
  SCALENOEHEDRAL = 'scalenohedral',
  TETRAHEDRAL = 'tetrahedral',
  BOTRYOIDAL = 'botryoidal',
  GLOBULAR = 'globular',
  MAMMILLARY = 'mammillary',
  RENIFORM = 'reniform'
};
